name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn
      - name: Build Production
        run: yarn build
      - name: Configure Git
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@users.noreply.github.com"
      - name: Push Production
        run: |
          git checkout --orphan production
          git add -f dist
          git commit -m "Initial Commit"
          git push -f origin production
